# https://taskfile.dev

version: "3"

tasks:
  poc-app-nested:
    desc: A POC app written in Go, but defined in nested Taskfile.
    cmds:
      - go run github.com/fredrikaverpil/poc-tasks/cmd/app@latest
    silent: false
